### ISSUE TITLE
UserモデルおよびGitHubログイン機能追加

### ISSUE THREAD

**Issue by shioimm** [Tama-rb/vimate#3]
## 背景
- Userモデルを元にその他主要機能を追加する
- Userモデルの追加に合わせてログイン機能を実装する

## ToDo
- usersテーブルおよびUserモデル追加
- `omniauth` `omniauth-github` 追加
- `dotenv-rails` および.envファイル追加
- ログイン・ログアウト・トップページ（暫定）用URL追加
- sessionsコントローラー追加
- sessionsヘルパー追加
- usersコントローラー追加
- users#indexテンプレート追加（暫定topページ）

**Comment by Shigeyuki-fukuda** [comment]
📝 RSpecのセットアップとテストコード追加は、一旦は別のプルリクでやりましょうかね 👍
